# Generated by Django 3.1.5 on 2021-04-25 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exercise.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile_pics')),
                ('publish_at', models.DateTimeField()),
                ('instagram_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.instagramaccount')),
                ('tags', models.ManyToManyField(to='exercise.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_points', models.IntegerField(default=0)),
                ('num_workouts', models.IntegerField(default=0)),
                ('avg_points', models.IntegerField(default=0)),
                ('current_location', models.CharField(default='Charlottesville', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Sports', 'Sports'), ('Yoga/Flexibility', 'Yoga/Flexibility')], default='Cardio', max_length=20)),
                ('location', models.CharField(choices=[('Indoors', 'Indoors'), ('Outdoors', 'Outdoors')], default='Indoors', max_length=8)),
                ('exercise_date', models.DateTimeField(null=True, validators=[exercise.models.Exercise.exclude_future_date], verbose_name='date completed')),
                ('time_taken', models.CharField(choices=[('Quick Workout (Between 1-29 min)', 'Quick Workout (Between 1-29 min)'), ('Longer Workout (Between 30-59 min)', 'Longer Workout (Between 30-59 min)'), ('Long Workout (Between 60 and 119 min)', 'Long Workout (Between 60 and 119 min)'), ('Very Long Workout (120 min or greater)', 'Very Long Workout (120 min or greater)')], default='Quick Workout (Between 1-29 min)', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.profile')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.profile')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
